export const galleryCategories = [
    'FINAL',
    'working-final',
    'proto-final',
    'prompts',
    'shade',
    'webgl',
    'selfies',
    'update',
    'visualization',
    'process',
    'proposal',
    'random',
    'MIDTERM',
    'GOL',
    'boids',
    'game over',
    'game on',
    'change',
    'character',
    'collection',
    'proto-collection',
    'listen!',
    'soundings',
    'gallery',
    'meme',
    'grids',
    'intro',
]

export default galleryCategories