export const galleryCategories = [
    'FINAL',
    'FINAL',
    'working-final',
    'proto-final',
    'update',
    'shade',
    'webgl',
    'selfies',
    'update',
    'visualizing',
    'pendulum',
    'proposal',
    'proposal',
    'MIDTERM',
    'MIDTERM',
    'proto-midterm',
    'boids',
    'landscape',
    'change',
    'sketchy',
    'player',
    'collection',
    'proto-collection',
    'listen!',
    'soundings',
    'gallery',
    'meme',
    'grids',
    'intro',
]

export default galleryCategories